<a href="https://colab.research.google.com/github/VinayProgram/pytorch/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as plt

In [4]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
# That means although scalar is a single number, it's of type torch.Tensor.

In [6]:
# to check the dimension of an vector we can use ndim attribute
scalar.ndim
# to reterieve the scalar number
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
#vector declarion
vector
#dimensions of vector
vector.ndim
#this will tell the shape of vector which conssits of
vector.shape


torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape


torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:

# Basic operations

tensor = torch.tensor([1,2,4])
tensor+10
tensor*10


#matrix mutliplication
tensor1 =torch.tensor([3,4,5])
tensor*tensor1


#same size cannot be multipled
randtensor1 = torch.rand([1,3])
randtensor = torch.rand([3,1])
randtensor.matmul(randtensor1)

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
#what the nn linear actully does
# suppooose we have a tensor/vector in pointed on a graph with xyz and then we want to create a linear points between xyz we use nn.Linear
#what happens when we use matrix in tensor
# Then the random weights in nn.Linear and the numbers from torch.rand() will be exactly the same each run.
# torch.manual_seed(42)

layer = nn.Linear(in_features=12, out_features=1)  # 3 inputs → 2 outputs
x = torch.tensor([[1.0, 2.0, 3.0,
                   12,23,45,
                   23,45,34,
                   2,2,1
                   ]])  # shape: (1, 3)
#what if we use tensor matrix
#if you turn on manual seed random number generation will change to its origin
randomMatrix = torch.rand([12,12])
print(randomMatrix)
y = layer(randomMatrix)  # shape: (1, 2)
print(y)


tensor([[6.7817e-01, 8.3602e-01, 7.4523e-01, 7.6926e-01, 1.7497e-01, 2.6501e-01,
         4.9947e-02, 2.2872e-01, 4.6034e-01, 8.4789e-03, 2.5052e-01, 2.9152e-01],
        [4.6272e-01, 2.1329e-01, 5.8819e-01, 2.8669e-01, 4.9662e-01, 8.2654e-01,
         3.1754e-01, 9.2079e-01, 5.4930e-01, 7.5128e-01, 3.6803e-01, 1.3303e-01],
        [9.3268e-02, 6.1069e-02, 2.4979e-01, 7.5179e-01, 7.4073e-01, 6.1164e-01,
         3.1913e-01, 5.5329e-01, 7.2259e-01, 6.6583e-03, 7.7702e-01, 5.5249e-01],
        [1.5872e-01, 2.2732e-01, 1.5829e-01, 9.5427e-01, 1.5172e-01, 8.7261e-01,
         6.6697e-01, 3.2021e-01, 9.0430e-01, 4.1041e-01, 6.6381e-01, 6.2132e-01],
        [6.9148e-01, 9.8017e-01, 7.0394e-01, 6.2511e-01, 8.8025e-01, 8.3117e-01,
         9.7183e-01, 6.3754e-01, 4.6151e-01, 5.2988e-01, 9.5236e-01, 5.6250e-01],
        [4.5501e-01, 6.3246e-01, 9.1407e-01, 6.1739e-01, 4.5634e-01, 4.1950e-01,
         6.5290e-01, 3.4186e-01, 7.8337e-01, 9.7028e-01, 9.5234e-01, 2.8191e-01],
        [2.2039e-01, 7

In [11]:
x = torch.tensor([2.0, 4.0, 6.0])
mean_val = torch.mean(x)
print(mean_val)  # tensor(4.)

tensor(4.)


In [12]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [13]:

# Reshaping, stacking, squeezing and unsqueezing

x = torch.arange(1., 9.)
x, x.shape

x_reshaped = x.reshape(2,2,2)
x_reshaped

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [31]:
##Creating A Random Tensor
torch.manual_seed(42)
rdmtensor= torch.rand(7,7)
print(torch.rand(7,7))
rdmtensor2 = torch.rand(1,7)
rdmtensor*rdmtensor2



tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])


tensor([[2.8475e-01, 1.4826e-02, 8.1805e-02, 5.9947e-01, 1.6946e-01, 8.2357e-02,
         1.3130e-01],
        [2.5614e-01, 1.5243e-02, 2.8457e-02, 5.8403e-01, 2.5762e-01, 1.1916e-01,
         2.9052e-01],
        [2.3918e-01, 6.9575e-03, 1.8919e-01, 3.5863e-01, 1.1570e-01, 8.5996e-02,
         1.3798e-01],
        [1.4245e-01, 4.8109e-03, 1.7770e-01, 6.5811e-02, 1.1696e-01, 4.9178e-02,
         1.0202e-01],
        [1.7660e-01, 9.9816e-05, 2.0331e-01, 4.7034e-02, 3.8453e-01, 7.9933e-02,
         1.7278e-01],
        [2.6109e-01, 9.3639e-03, 1.9315e-01, 3.4661e-01, 1.4857e-01, 8.6941e-02,
         1.8648e-01],
        [2.2929e-01, 1.5334e-02, 1.6859e-01, 1.7586e-01, 3.4227e-01, 8.0790e-02,
         3.8580e-01]])